### ISSUE TITLE
Prerequisite: fibjs>0.25.0 ？

### ISSUE THREAD

**Issue by moonghg** [fibjs/fib-types#4]
太棒了，感谢！

> Prerequisite: fibjs > 0.25.0
这个是不是笔误？>= 0.24.0 ？

[fibjs-issues-405](https://github.com/fibjs/fibjs/issues/405)

**Comment by richardo2016** [comment]
@milkman2014 That's not mistake, fibjs group haven't publish next version(`0.25.0`), which includes internal typescript. So this repo is meaningless now --- but valid after fibjs `0.25.0` published : )
